### ISSUE TITLE
WNF150F512ET32 / TLSR8269 supported?

### ISSUE THREAD

**Issue by kodidu** [pvvx/TlsrTools#2]
Hello!

@pvvx Thanks for this tool!

Sadly I have to use google translate to get some idea about the message output of the program, so I ask here for further info.

Everything looks ok so far.
I click on Connect/Open and the chip is identified: SoC ID: 0x5327 Chip: TLSR8269.
I click on Activate => Activate OK messages appears in status bar.
What does "FLoader not load" mean? Is this an error after clicking activate?

Now i dumped the original firmware of the device 0x0000. (size 0x80000 512KiB) => no errors file seems to be ok, i could find some strings like the bluetooth device name in this dump

Then I compiled my own program via the telink sdk => got a app.bin
So I tried to flash it.
reset => activate => Flash erase => Fwrite => could not see any errors, but app.bin does not run, still on old vendor firmware.

As test i tried reset => activate => Flash erase => Fread => Flash data is not empty => still contains vendor firmware.

Is this some error in the tool?
Or do I have some locked chip. The IC package says WNF150F512ET32, so maybe it is some custom one? TLSR8269F512ET32 would be the official marking.

**Comment by pvvx** [comment]
WNF150F512ET32 - Flash ID?
![image](https://user-images.githubusercontent.com/12629515/203060306-3444a4cf-2727-4896-b15e-0bea59953044.png)

WNF150 - https://www.nanosic.com/product_xq/id-3.html ?

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/203064702-664bbd3b-5c62-4c21-ac64-d1816edaafe3.png)

'Test' is a Flash commands...

**Comment by kodidu** [comment]
>WNF150 - https://www.nanosic.com/product_xq/id-3.html ?

Yes, seems to be this chip. QFN 5x5mm
Tracing the pinout of my device looks like this chip is 1:1 TLSR8269F512ET32.
SWS is at pin 14.
ANT is at pin 37.
Analog MIC (AMIC) is at pin 26+27 (differential signal)
...

My readout:
![xxx](https://user-images.githubusercontent.com/75952322/203138557-91b035fb-e3f3-4b32-8e7b-5d937b6f788d.JPG)
![image](https://user-images.githubusercontent.com/75952322/203139592-78c32a68-27d1-4f1d-a2a4-5d14cdabad6a.png)

**Comment by pvvx** [comment]
Flash MD25D40 ID: 514013
http://www.firstjit.com/Uploadfiles/20150114093141359.pdf
MD25D40 - Software protection mode.
 _The Chip Erase (CE) command is executed if the Block Protect (BP2, BP1, BP0) bits are all 0 or all 1. The Chip Erase (CE) command is not excuted if any sector is under protection._ 

Read Status Register (Flash CMD 0x05)
![image](https://user-images.githubusercontent.com/12629515/203176948-764ea032-3df1-46b8-9628-9ba1262eb70f.png)
![image](https://user-images.githubusercontent.com/12629515/203176961-03c42d42-f568-4bbd-8bba-0434d5d1bbd2.png)

**Comment by pvvx** [comment]
TlsrTool.exe v0.0.1.6
Added write value 0x02 into flash status register  before the erase all flash command.

**Comment by kodidu** [comment]
Thank you!
Flash erase is working! Write + read back is also matching!
My compiled app starts and I can connect!

Now I have to study the telink sdk, if there are some hiccups because of WNF150F512ET32 vs TLSR8269F512ET32.
